### ISSUE TITLE
Open in Windows "library" folders

### ISSUE THREAD

**Issue by fazlee712** [Fr4cK5/spear#1]
Usage mentions:

> Select Dir Select another directory manually. As an alternative to this, you can just navigate to your desired directory and press LCtrl+LWin+L.
> 
> NOTE The explorer integration feature only works in "non-library" directories. Windows library directories are "Documents", "Pictures", "This PC", ...

but with a short bit of code you can retrieve the current active directory in the explorer

Example where I use it to launch a terminal window at the current location (or defaults to 'Desktop' if no explorer window focused) with CapsLock + C hotkey:

```
c::
CurrentExplorerPath := A_Desktop
if explorerHwnd := WinActive("ahk_class CabinetWClass")
{
    for window in ComObjCreate("Shell.Application").Windows
    {
        if (window.hwnd = explorerHwnd)
        {
        	if SubStr(window.Document.Folder.Self.Path,-1)=":\"
        		CurrentExplorerPath := window.Document.Folder.Self.Path
        	else
            	CurrentExplorerPath := """" . window.Document.Folder.Self.Path . """"
        }

    }
}
switch A_ComputerName
{
	case "my-pc","other-pc":
	{
		if GetKeyState("Shift", "P")
			Run, *RunAs, wt.exe --startingDirectory %CurrentExplorerPath%
		else
			Run wt.exe --startingDirectory %CurrentExplorerPath%
	}
	default:
		Run % ComSpec . " " . CurrentExplorerPath
}
return
```

https://github.com/Fr4cK5/spear/assets/10059800/4f231a76-d760-480b-b698-6373efc4c670

**Comment by Fr4cK5** [comment]
Thank you for this, I'm going to integrate it into spear as soon as possible.

**Comment by fazlee712** [comment]
Hey I just tested this now - it works in library folders but freezes/crashes in drive root folders (e.g. C:\ or D:\)

I had this same problem with my bit of code that I use to launch CMD in the current folder - I had to add this part to the code to exclude the quotes in `CurrentExplorerPath` just for those root folders and then it worked. Not sure if Spear needs something similar as well

```
                if SubStr(window.Document.Folder.Self.Path,-1)=":\"
        		CurrentExplorerPath := window.Document.Folder.Self.Path
        	else
            	CurrentExplorerPath := """" . window.Document.Folder.Self.Path . """"
```

**Comment by Fr4cK5** [comment]
I am unable to reproduce the crash you are talking about.

I'm assuming you ***think*** Spear has crashed when in reality it's frozen because it's caching the whole file hierarchy.
In my testing I've frequently seen both, an unresponsive UI and/or a completely white window, but - as said - this is normal. Also, keep in mind that the caching speed almost solely relies on your drive's speed. If you're running an HDD or standard SATA SSD like me, instead of an m.2 Nvme SSD, low caching performance is to be expected.

I've found and fixed some weird behavior regarding caching my main C:/ drive although this didn't affect my secondary D:/ drive. (Changes will be up in a few minutes if I don't find any other weirdness)

Here you see that I cached my whole C:/ drive:

![its-working](https://github.com/Fr4cK5/spear/assets/96948888/c252cde3-e22c-4543-8aad-54e4dc14e4be)

Proof of the memory usage:
If you're running this in VSCode, you need to unfold the process tree to see Spear's memory usage.

![expand-vscode](https://github.com/Fr4cK5/spear/assets/96948888/f9ceeb0b-ce9f-470b-8a51-217583c13f4c)
